CXXFLAGS  = -O3 -m64
CXXFLAGS += -Wall
CXXFLAGS += -Wextra
CXXFLAGS += -pedantic
CXXFLAGS += -Weffc++
CXXFLAGS += -std=c++17

all:
	$(CXX) -c *.cpp $(CXXFLAGS)
	$(CXX) *.o -o wavelength.exe $(CXXFLAGS)
